namespace: monk-redis-cluster-haproxy

stack:
  defines: process-group
  runnable-list:
    - monk-redis-cluster-haproxy/rds1
    - monk-redis-cluster-haproxy/rds2
    - monk-redis-cluster-haproxy/rds3
    - monk-redis-cluster-haproxy/haproxy
    - monk-redis-cluster-haproxy/sentinel1
  variables:
    rds_master:
      value: <- get-hostname("monk-redis-cluster-haproxy/rds1", "monk-rds1")  split(".dns.podman") join("")
    rds_slave1:
      value: <- get-hostname("monk-redis-cluster-haproxy/rds2", "monk-rds2")  split(".dns.podman") join("")
    rds_slave2:
      value: <- get-hostname("monk-redis-cluster-haproxy/rds3", "monk-rds3")  split(".dns.podman") join("")
    redis_image_tag: "7.0"
    redis1_port: 6388
    redis2_port: 6389
    redis3_port: 6387
    rds_haproxy_port: 6379
    rds_haproxy_stats_port: 9000
    redis_disable_commands: FLUSHALL 
    redis_password: bitnami
    redis_empty_password: yes
    redis_io_thread: 1
    redis_io_threads_do_reads: yes
    redis_nodes_list: 