---
namespace: monk-redis-cluster

stack:
  defines: process-group

  runnable-list:
    - monk-redis-cluster/rds1
    - monk-redis-cluster/rds2
    - monk-redis-cluster/rds3
    - monk-redis-cluster/sentinel1

  variables:
    redis_image_tag: "7.0"
    redis1_port: 6388
    redis2_port: 6389
    redis3_port: 6387
    redis_disable_commands: FLUSHALL
    redis_password: bitnami
    redis_empty_password: no
    redis_io_thread: 1
    redis_io_threads_do_reads: yes