---
namespace: redis-cluster

stack:
  defines: process-group
  metadata:
    name: Redis Clustered
    description: |
      A leader-follower clustered Redis setup consists of one leader node and two follower nodes. The leader node is responsible for handling all write operations and replicating data to the follower nodes.

      The follower nodes are responsible for handling read operations and can also act as a failover mechanism in case the leader node fails. This setup provides high availability and scalability for Redis applications.

    website: https://redis.io
    publisher: monk.io
    icon: https://cdn.icon-icons.com/icons2/2415/PNG/512/redis_original_wordmark_logo_icon_146369.png
    version: 1.0
  runnable-list:
    - redis-cluster/redis-leader
    - redis-cluster/redis-follower-1
    - redis-cluster/redis-follower-2
    - redis-cluster/sentinel
  variables:
    leader_port:
      type: string
      value: 6387
    follower-1_port:
      type: string
      value: 6388
    follower-2_port:
      type: string
      value: 6389
    disable_commands:
      type: string
      value: FLUSHALL
    password:
      type: string
      value: bitnami
    empty_password:
      type: string
      value: 'no'
    io_thread:
      type: string
      value: 1
    io_threads_do_reads:
      type: string
      value: 'yes'
